application: linebot-koreeda
module: default
version: alpha-001
runtime: go
api_version: go1

handlers:
- url: /
  mime_type: text/html
  static_files: public/index.html
  upload: public/index.html

- url: /.*
  script: _go_app